import java.util.*;
import java.util.stream.*;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
		var collect = Stream.of(42).collect(Collectors.toUnmodifiableList());
		System.out.println(collect);
	}
}
