import java.time.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

DayOfWeek dayOfWeek = LocalDate.now().getDayOfWeek();
		String typeOfDay = switch (dayOfWeek) {
			case MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY -> "Working Day";
			case SATURDAY, SUNDAY -> "Day Off";
		};
    }
}
